M48
; DRILL file {KiCad (6.0.1)} date Wed Mar 23 10:27:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-23T10:27:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X2.985Y-5.3146
T2
X2.985Y-2.8134
X3.615Y-4.9866
T0
M30
